### ISSUE TITLE
size mismatch error

### ISSUE THREAD

**Issue by alireza-kr** [ViCCo-Group/thingsvision#123]
Hi

Recently, I added [a pre-trained AlexNet model](https://github.com/ViCCo-Group/thingsvision/blob/master/thingsvision/custom_models/alexnet_salobjsub.py) to your custom models. When I download the model from OSF, I get size mismatch error:

```
Error(s) in loading state_dict for AlexNet:
	size mismatch for features.0.weight: copying a param with shape torch.Size([96, 3, 11, 11]) from checkpoint, the shape in current model is torch.Size([64, 3, 11, 11]).
	size mismatch for features.0.bias: copying a param with shape torch.Size([1, 1, 1, 96]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for features.3.weight: copying a param with shape torch.Size([256, 48, 5, 5]) from checkpoint, the shape in current model is torch.Size([192, 64, 5, 5]).
	size mismatch for features.3.bias: copying a param with shape torch.Size([1, 1, 1, 256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for features.6.weight: copying a param with shape torch.Size([384, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 192, 3, 3]).
	size mismatch for features.6.bias: copying a param with shape torch.Size([1, 1, 1, 384]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for features.8.weight: copying a param with shape torch.Size([384, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 384, 3, 3]).
	size mismatch for features.8.bias: copying a param with shape torch.Size([1, 1, 1, 384]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for features.10.weight: copying a param with shape torch.Size([256, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for features.10.bias: copying a param with shape torch.Size([1, 1, 1, 256]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for classifier.1.weight: copying a param with shape torch.Size([1, 1, 4096, 9216]) from checkpoint, the shape in current model is torch.Size([4096, 9216]).
	size mismatch for classifier.1.bias: copying a param with shape torch.Size([1, 1, 1, 4096]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for classifier.4.weight: copying a param with shape torch.Size([1, 1, 4096, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
	size mismatch for classifier.4.bias: copying a param with shape torch.Size([1, 1, 1, 4096]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for classifier.6.weight: copying a param with shape torch.Size([1, 1, 5, 4096]) from checkpoint, the shape in current model is torch.Size([565, 4096]).
	size mismatch for classifier.6.bias: copying a param with shape torch.Size([1, 1, 1, 5]) from checkpoint, the shape in current model is torch.Size([565]).
```

Do you have any suggestions to solve this issue?

**Comment by Alxmrphi** [comment]
Can you please provide the architecture definition of your custom model? I think there is a misspecification somewhere, and it would be helpful to compare existing AlexNet definition with the one you've added, to better spot where the misalignment takes place. Then it should be easier to see what needs to change to fix the bug you're seeing.

**Comment by alireza-kr** [comment]
I used pre-trained weights from [salient object subitizing (SOS) image dataset](https://cs-people.bu.edu/jmzhang/sos.html). [This](https://arxiv.org/abs/1607.07525) is the reference paper. The AlexNet has been trained using Caffe and the weight is available [here](https://gist.github.com/jimmie33/0585ed9428dc5222981f) and you can find the model definition as a [prototxt file](https://gist.githubusercontent.com/jimmie33/0585ed9428dc5222981f/raw/ec5b38a662bfcd140dd1ce15a2949b38ef5630c2/deploy.prototxt) in the same link. I converted the Caffe file using [caffemodel2pytorch](https://github.com/vadimkantorov/caffemodel2pytorch) and change the layers’ name to be compatible with the THINGSvision naming convention.

**Comment by alireza-kr** [comment]
Hi
I was wondering whether you have any comments on why the custom AlexNet is not working?

**Comment by andropar** [comment]
Hi Ali,

First of all thanks for adding the model! The version of AlexNet they used in their paper and the one implemented in torchvision are not entirely identical. If you compare the model definition from your prototxt file with the torchvision model: 
```python
AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
    (2): ReLU(inplace=True)
    (3): Dropout(p=0.5, inplace=False)
    (4): Linear(in_features=4096, out_features=4096, bias=True)
    (5): ReLU(inplace=True)
    (6): Linear(in_features=4096, out_features=565, bias=True)
  )
)
```
you'll see that they differ in the number of feature maps used in the convolutional layers (e.g. 96 in the Caffe version vs 64 in the torchvision version). Also, you defined the number of outputs as 565, while it's only 5 in the paper. 

My suggestion would be to alter the [torchvision implementation](https://github.com/pytorch/vision/blob/main/torchvision/models/alexnet.py) to fit your model and add it to the custom model class you created for thingsvision. It also seems like you might have to `.squeeze` the weights you get from caffemodel2pytorch (to remove the unnecessary dimensions from the biases and fully connected layer weights).

Let us know if this works and if you run into any other issues!

**Comment by LukasMut** [comment]
@alireza-kr @andropar can we close this issue or is there still something that needs to be resolved on our end?

**Comment by alireza-kr** [comment]
Nothing to be resolved on your side. Thank you @LukasMut
