### ISSUE TITLE
Fix error thrown when passing `None` as `model_parameters` for `get_extractor`

### ISSUE THREAD

**Issue by andropar** [ViCCo-Group/thingsvision#137]
The `model_parameters` argument for `get_extractor` is set to `None` as the default. This will cause an error when omitting it from the function call, as the extractors that use it will attempt to get values from it with `.get()`, which only works with dictionaries. 

An easy, ugly fix would be to just use `model_parameters = {}` instead, which should be fine. Otherwise we have to check for `None` somewhere.

**Comment by LukasMut** [comment]
Could you submit a PR that does the easy fix and we'll figure out a more elegant solution in the future?
