### ISSUE TITLE
Add more output options (i.e. txt, mat)

### ISSUE THREAD

**Issue by andropar** [ViCCo-Group/thingsvision#142]
For those not using python for data analysis, it would be nice to also be able to store features as `mat` or `txt` files.

**Comment by LukasMut** [comment]
I am not sure what this issue is referring to

**Comment by andropar** [comment]
Sorry, wrote this in a bit of a rush 😅 Current options for saving features are numpy arrays or pytorch tensors, but if someone uses thingsvision only for extracting and wants to do the analysis in e.g. Matlab, an option to save features in a language agnostic format (.txt) would be nice and easy to implement.

**Comment by LukasMut** [comment]
These options exist AFAIK (see [here](thingsvision/utils/storing/helpers.py))
