### ISSUE TITLE
small issues with CLI

### ISSUE THREAD

**Issue by KogniJannis** [ViCCo-Group/thingsvision#162]
when trying the commands from ["getting started"](https://thingsvision.github.io/GettingStarted.html) in the documentation, it looks to me like, the parser does not properly find mode_parameters if show-model  is called
![image](https://github.com/ViCCo-Group/thingsvision/assets/104796901/6ca2c7cf-d079-42bf-b157-7075597b1555)
also I think there is a small typo in the example calls where "extract_features" should be "extract-features"
Best, Jannis

**Comment by LukasMut** [comment]
@KogniJannis Hi Jannis! Thanks for pointing this out! This is addressed in PR #163. PTAL. As soon as this PR is merged into the main branch and I update the patch version of `thingsvision` on PyPi this should no longer be an issue.

**Comment by LukasMut** [comment]
PS.: I also fixed the typo that you spotted.

**Comment by KogniJannis** [comment]
thank you!
