### ISSUE TITLE
Trying to run gLocal

### ISSUE THREAD

**Issue by ShreyaKapoor18** [ViCCo-Group/thingsvision#177]
Hi @LukasMut 

https://github.com/ViCCo-Group/thingsvision/blob/ad903f383a8e647057010bd1618b0b8770e8f3a7/thingsvision/utils/alignment/transforms.py#L14

I wanted to ask if the URL is still valid?
It would be nice if I can get this function working?

Best regards,
Shreya

**Comment by Alxmrphi** [comment]
Hi Shreya,

Can you try editing the file and replace the URL with the following?

```https://github.com/LukasMut/gLocal/tree/main/transforms```

Hopefully that works for you and we can then update stuff on our end.

Alex

**Comment by ShreyaKapoor18** [comment]
thanks! this works! Can we do glocal for custom models?

**Comment by Alxmrphi** [comment]
Ah I read the original post and was going to wait for @LukasMut to respond as this is in his personal repo. I didn't see the part about the error until just now. I will still wait to see if Lukas knows the best way to go about it as this comes more directly from his work. I think instinctively I would set `allow_pickle=False` in the load function and see if that works. Otherwise, this is something that can be amended in an update to the library once it's clear what the correct paths / loading process is.

**Comment by ShreyaKapoor18** [comment]
Thanks for your reply Alex. What I did download the temp.npz directly and it worked for me!

**Comment by LukasMut** [comment]
> Hi @LukasMut 
> 
> 
> 
> https://github.com/ViCCo-Group/thingsvision/blob/ad903f383a8e647057010bd1618b0b8770e8f3a7/thingsvision/utils/alignment/transforms.py#L14
> 
> 
> 
> I wanted to ask if the URL is still valid?
> 
> It would be nice if I can get this function working?
> 
> 
> 
> Best regards,
> 
> Shreya

This url should still be valid. Doesn't it work?

**Comment by Alxmrphi** [comment]
Original link gives **_400: Bad Request_** error for me.

**Comment by LukasMut** [comment]
> Original link gives **_400: Invalid Request_** error for me.

That is weird. We use this link in a different project and don't encounter any problems. Let me look into this

**Comment by LukasMut** [comment]
@Alxmrphi @ShreyaKapoor18 Everything should work as expected. There is no error. The link [`https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/`](https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/) will raise _**400: Invalid request**_ because raw GitHub links are only valid for files (and this link does not point to a file). However, the [transform code](https://github.com/ViCCo-Group/thingsvision/blob/ad903f383a8e647057010bd1618b0b8770e8f3a7/thingsvision/utils/alignment/transforms.py#L39-L64) uses this link and adds model (e.g.`OpenCLIP_ViT-L-14_laion400m_e32`) and module (e.g. `visual`) subfolders to it and finally appends the file name `transform.npz` to it. If you copy [`https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz`](https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz) into an open tab (or just click on that link) it will automatically download the transform.

@ShreyaKapoor18 What was the original error you were facing?

**Comment by ShreyaKapoor18** [comment]
> @Alxmrphi @ShreyaKapoor18 Everything should work as expected. There is no error as far as I can see. The link [`https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/`](https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/) will raise _**400: Invalid request**_ because raw GitHub links are only valid for files (and this link does not point to a file). However, the [transform code](https://github.com/ViCCo-Group/thingsvision/blob/ad903f383a8e647057010bd1618b0b8770e8f3a7/thingsvision/utils/alignment/transforms.py#L39-L64) uses this link and adds model (e.g.`OpenCLIP_ViT-L-14_laion400m_e32`) and module (e.g. `visual`) subfolders to it and finally appends the file name `transform.npz` to it. If you copy [`https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz`](https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz) into an open tab in your browser (or just click on that link) it will automatically download the transform.
> 
> @ShreyaKapoor18 What was the original error you were facing?

Hi @LukasMut  and @Alxmrphi 

Thanks for your reply. I think the issue was that I was trying this with a custom model and that did not directly
translate to the following link such as `https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz` 
but what worked for me was directly downloading the transform.npz into my directory. 

  File "/Users/shreya/Documents/GitHub/objaverse_training_2/things_vision.py", line 105, in <module>
    aligned_features = e.align(
  File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/thingsvision/core/extraction/torch.py", line 231, in align
    transform = gLocal(
  File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/thingsvision/utils/alignment/transforms.py", line 47, in __init__
    self.transform = self.load_transform_from_remote()
  File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/thingsvision/utils/alignment/transforms.py", line 58, in load_transform_from_remote
    transform = np.load("temp.npz", allow_pickle=True)
  File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/numpy/lib/npyio.py", line 467, in load
    raise pickle.UnpicklingError(
_pickle.UnpicklingError: Failed to interpret file 'temp.npz' as a pickle

this error occured since it did download the file but it was corrupted due to not being able to find the correct path. 

Best regards,
Shreya Kapoor

**Comment by LukasMut** [comment]
> > @Alxmrphi @ShreyaKapoor18 Everything should work as expected. There is no error as far as I can see. The link [`https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/`](https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/) will raise _**400: Invalid request**_ because raw GitHub links are only valid for files (and this link does not point to a file). However, the [transform code](https://github.com/ViCCo-Group/thingsvision/blob/ad903f383a8e647057010bd1618b0b8770e8f3a7/thingsvision/utils/alignment/transforms.py#L39-L64) uses this link and adds model (e.g.`OpenCLIP_ViT-L-14_laion400m_e32`) and module (e.g. `visual`) subfolders to it and finally appends the file name `transform.npz` to it. If you copy [`https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz`](https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz) into an open tab in your browser (or just click on that link) it will automatically download the transform.
> 
> > 
> 
> > @ShreyaKapoor18 What was the original error you were facing?
> 
> 
> 
> Hi @LukasMut  and @Alxmrphi 
> 
> 
> 
> Thanks for your reply. I think the issue was that I was trying this with a custom model and that did not directly
> 
> translate to the following link such as `https://raw.githubusercontent.com/LukasMut/gLocal/main/transforms/OpenCLIP_ViT-L-14_laion400m_e32/visual/transform.npz` 
> 
> but what worked for me was directly downloading the transform.npz into my directory. 
> 
> 
> 
>   File "/Users/shreya/Documents/GitHub/objaverse_training_2/things_vision.py", line 105, in <module>
> 
>     aligned_features = e.align(
> 
>   File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/thingsvision/core/extraction/torch.py", line 231, in align
> 
>     transform = gLocal(
> 
>   File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/thingsvision/utils/alignment/transforms.py", line 47, in __init__
> 
>     self.transform = self.load_transform_from_remote()
> 
>   File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/thingsvision/utils/alignment/transforms.py", line 58, in load_transform_from_remote
> 
>     transform = np.load("temp.npz", allow_pickle=True)
> 
>   File "/Users/shreya/anaconda3/envs/thingsvision/lib/python3.9/site-packages/numpy/lib/npyio.py", line 467, in load
> 
>     raise pickle.UnpicklingError(
> 
> _pickle.UnpicklingError: Failed to interpret file 'temp.npz' as a pickle
> 
> 
> 
> this error occured since it did download the file but it was corrupted due to not being able to find the correct path. 
> 
> 
> 
> Best regards,
> 
> Shreya Kapoor
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I see what you are saying. You want to be able to provide paths to custom gLocal transform that you trained yourself, correct?

**Comment by LukasMut** [comment]
@ShreyaKapoor18 @Alxmrphi Since I haven't gotten a response for more than 4 months, I am closing this issue now.
