### ISSUE TITLE
import error - scikit image

### ISSUE THREAD

**Issue by AlGoulas** [ViCCo-Group/THINGSvision#2]
Hello there,

I would like to try your tool but there are some issue during import (please see below).

I have re-installed scikit-image  but his did not help. Any ideas?

Thank you.

ImportError: dlopen(/anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/_shared/geometry.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/_shared/../.dylibs/libomp.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-4bb7f3f9eb3d>", line 1, in <module>
    import thingsvision.vision as vision

  File "/anaconda3/envs/coactivations/lib/python3.9/site-packages/thingsvision/vision.py", line 67, in <module>
    from skimage.transform import resize

  File "/anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/__init__.py", line 124, in <module>
    _raise_build_error(e)

  File "/anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/__init__.py", line 102, in _raise_build_error
    raise ImportError("""%s

ImportError: dlopen(/anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/_shared/geometry.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/_shared/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /anaconda3/envs/coactivations/lib/python3.9/site-packages/skimage/_shared/../.dylibs/libomp.dylib
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html

**Comment by LukasMut** [comment]
Quick question: did everthing work correctly during the installation of thingsvision via pip?

**Comment by LukasMut** [comment]
Could you try uninstalling thingsvision via "pip uninstall thingsvision" and then installing the latest version?

**Comment by AlGoulas** [comment]
Ahh great! now it works (in the sense that it is imported). I will let you know if anything else arise. Many thanks for your help! Looks like a really nice toolbox

**Comment by LukasMut** [comment]
Thanks for your feedback! I hope it facilitates your work and you find it useful :)
