### ISSUE TITLE
CORnet inconsistent vector length

### ISSUE THREAD

**Issue by heidamaria** [ViCCo-Group/THINGSvision#46]
When running images through CORnet-z, the output layer for IT, as far as I understand from the CORnet preprint (https://www.biorxiv.org/content/10.1101/408385v1.full.pdf), is supposed to be 7x7x512 which when flattened would be a vector of length 25088. This is indeed what happens when apply_center_crop is set to True. However, when it is set to False, the output vectors of the same images (224 x 224 pixels), same layer/module, end up being of size 32768. 
This behavior does not appear to be layer specific, I e.g. also tested it for the V1 output layer and the vector length also depends on whether center crop is applied or not. 

I am not quite sure if this is a bug or "normal" behavior that I then just do not quite understand.

**Comment by LukasMut** [comment]
Hi Heida! We will take a look at this. If this happens to be something that's CORnet-specific, you probably want to raise that issue on the CORnet GitHub repository. Do you see this behavior for any other model or doe is *only* happen for CORnet? 

@hahahannes, could you take a detailed look at how you've implemented the `apply_center_crop` flag? Do you see anything that might interfere with the forward pass of a model?

**Comment by hahahannes** [comment]
Mh strange! I thought the center crop option would only occur in the image transformations before the forward pass

**Comment by hahahannes** [comment]
I guess this happens with PyTorch?

**Comment by heidamaria** [comment]
> Hi Heida! We will take a look at this. If this happens to be something that's CORnet-specific, you probably want to raise that issue on the CORnet GitHub repository. Do you observe this behavior for any other model or does it _exclusively_ happen for CORnet?
> 
> @hahahannes, could you take a detailed look at how you've implemented the `apply_center_crop` flag? Do you see anything that might interfere with the forward pass of a model?

I simply put it as:
apply_center_crop = False 
or 
apply_center_crop = True

I was working from your colab code from a couple of days ago, and I barely touched the rest of it. I did output it as a .mat file, in case that makes a difference somehow.

**Comment by heidamaria** [comment]
> I guess this happens with PyTorch?

This is PyTorch, yes.

**Comment by LukasMut** [comment]
@hahahannes Is this still an open issue or can we close it?
