### ISSUE TITLE
Circular imports in `thingsvision.vision`

### ISSUE THREAD

**Issue by florianmahner** [ViCCo-Group/THINGSvision#51]
Cannot import `thingsvision.dataaset.ImageDataset` as a stand-alone, without prior import of `thingsvision.vision`. Code to reproduce:

```
from thingsvision.dataset import ImageDataset
```
throws: `ImportError: cannot import name 'ImageDataset' from partially initialized module 'thingsvision.dataset' (most likely due to a circular import)`. Temporary fix is:

```
import thingsvision.vision
from thingsvision.dataset import ImageDataset
```

**Comment by LukasMut** [comment]
Feel free to open a PR.

**Comment by LukasMut** [comment]
Is this still an open issue @hahahannes @florianmahner ? If so, we would be happy if you @florianmahner could open a PR to resolve that issue?
