### ISSUE TITLE
UserWarning from torchvision/transforms

### ISSUE THREAD

**Issue by PhilippKaniuth** [ViCCo-Group/THINGSvision#60]
OS: macOS 10.14.6 (18G9323) (I know... ask my IT why)

I created and activated a fresh conda env using the [environment.yml](https://github.com/ViCCo-Group/THINGSvision/blob/master/envs/environment.yml). I did not install any additional packages.

```
device = 'cuda' if torch.cuda.is_available() else 'cpu'
batch_size = 68
model_name = 'clip-ViT'
module_name = 'visual'
backend = 'pt'
clip = True
out_path = ...
```

everything works as expected until I execute 

```
dl = vision.load_dl(root,
                    out_path=out_path,
                    batch_size=batch_size,
                    transforms=model.get_transformations(),
                    backend=backend,
                    file_names=file_names)
```
                              
Which outputs:
```bash
    /Users/kaniuth/Desktop/extractivations/conda_env/lib/python3.8/site-packages/torchvision/transforms/transforms.py:332:
    UserWarning: Argument interpolation should be of type InterpolationMode instead of int. 
    Please, use InterpolationMode enum. warnings.warn(
```

The pipeline seems to continue normally; I can extract and save activations just fine. I just don't know whether that warning has any consequences on the extracted activations?

That warning did not occur with earlier versions of THINGSvision.

**Comment by hahahannes** [comment]
I think thats the cause/solution: https://github.com/aitorzip/PyTorch-CycleGAN/issues/33#issuecomment-888162951
Which we would need to change here: https://github.com/ViCCo-Group/THINGSvision/blob/master/thingsvision/model_class.py#L380
Seems like it is not influencing much.
