### ISSUE TITLE
Torchvision compatibility

### ISSUE THREAD

**Issue by LukasMut** [ViCCo-Group/THINGSvision#65]
Enable compatibility with most recent torchvision version (>= 0.13.0)

**Comment by LukasMut** [comment]
I am thinking about either a dictionary, a named tuple, or a (custom) class that maps the names of the models (usually lower-case) to the names of the model weights (mostly a mix between upper-case and capitalization; see here: https://pytorch.org/vision/stable/models.html). We want to avoid a bunch of if-statements to obtain the corresponding model weights. Possibly appropriate thing to do is something along the lines of `model2weights[model_name] = getattr(f'{torchvision.models.weight_name}_DEFAULT`).

**Comment by andropar** [comment]
I thought about that too, but then I saw that using strings is also supported, so if we only care about the default weights, we could also create our models with `model(weights='DEFAULT')` instead, which might be a bit easier?

**Comment by LukasMut** [comment]
I agree that this is the easier thing to do but there is a problem with this approach. Each set of weights has its own image transformations which can only be accessed through the weight objects themselves. We would not be able to access the transformations by using the string approach. See example below.

```python
# Initialize the Weight Transforms
weights = ResNet50_Weights.DEFAULT
preprocess = weights.transforms()

# Apply it to the input image
img_transformed = preprocess(img)
```

**Comment by andropar** [comment]
Ah, I see, you're right. Then what about something like this:
```python
import inspect

weights_name = [
    member for member, _ in inspect.getmembers(torchvision.models) 
    if (member.lower.startswith(model_name) and 'Weights' in member)
][0]
 
# do some error handling in case nothing was found

weights = getattr(torchvision.models, f'{weights_name}').DEFAULT
```

Writing everything into a dict just seems like too much work, but we would have to think about whether something like this could produce any problems ...

**Comment by LukasMut** [comment]
Yes, that's actually a good idea! I like it. If `member` is a string, we could improve it by doing

```python
import re
import inspect

weights_name = [
    member for member, _ in inspect.getmembers(torchvision.models) 
    if re.search(f'(?=^{model_name})(?=.*weights$), member.lower())
][0]

# do some error handling in case nothing was found

weights = getattr(torchvision.models, f'{weights_name}').DEFAULT
```

**Comment by LukasMut** [comment]
Enabled. Note that a user has only access to DEFAULT weights with the current approach. We need to make this more flexible by defining extractor classes for each source.
