### ISSUE TITLE
Custom models

### ISSUE THREAD

**Issue by LukasMut** [ViCCo-Group/thingsvision#88]
Allow a user to add their own (pretrained) models without the necessity to upload them to `thingsvision` / make a PR

- pass a model object to the extractor class rather than a string for the model name (as is required now)

**Comment by andropar** [comment]
Implemented in #69 , but not tested yet

**Comment by LukasMut** [comment]
We have to add unittests. They are not implemented yet.

**Comment by LukasMut** [comment]
@andropar I think this is an issue we want to tackle next.
