### ISSUE TITLE
Add CLI  for quick and easy feature extraction

### ISSUE THREAD

**Issue by andropar** [ViCCo-Group/thingsvision#94]
I think a CLI would be a nice addition to the library for quickly extracting features without having to write a python script / making the library even easier to use. 

E.g. just being able to do `thingsvision extract --image_dir <path/to/images> --model_name <...> --source <...> --modules <module1> <...> --output_dir <path/to/out_dir>` and `thingsvision show_modules --model_name <...> --source <...>` would be nice.

**Comment by florianmahner** [comment]
Have recently done similar, can add this to the library.
