### ISSUE TITLE
Add thingsvision.__version__

### ISSUE THREAD

**Issue by Alxmrphi** [ViCCo-Group/thingsvision#99]
I have used a few various versions of THINGSvision and had to update code a fair bit, from `model_class` days to `Extractor` and now with the `get_extractor` style of usage. I don't want to update all my previous code in case I want to run it again, so I want to add in a version check but I noticed nothing is set up to access version information the 'traditional' way, i.e. 

```
>> thingsvision.__version__
AttributeError: module 'thingsvision' has no attribute '__version__'
```

Since there are a few different ways to go about implementing this, I wanted to raise an issue and see what could be defined as the way to implement this and then I don't mind submitting a PR to enact the change. Or if it was going to be updated in a future release, great, whatever. It'd just be useful to have access to version info in a Pythonic way.

**Comment by LukasMut** [comment]
@Alxmrphi could you take a stab at this and submit a PR?

**Comment by Alxmrphi** [comment]
Sure thing :)

**Comment by LukasMut** [comment]
@Alxmrphi Thanks!
